### ISSUE TITLE
Explicitly disallow unnamed Unicode codepoints in http://eel.is/c++draft/lex.charset#2

### ISSUE THREAD

**Issue by mzeren-vmw** [tahonermann/std-text-wg#3]
http://eel.is/c++draft/lex.charset#2 
Says:

> The character designated by the universal-character-name \UNNNNNNNN is that character whose character short name in ISO/IEC 10646 is NNNNNNNN; the character designated by the universal-character-name \uNNNN is that character whose character short name in ISO/IEC 10646 is 0000NNNN. If the hexadecimal value for a universal-character-name corresponds to a surrogate code point (in the range 0xD800–0xDFFF, inclusive), the program is ill-formed.

Should it also say:

> If the hexadecimal value for a universal-character-name is not named by ISO/IEC 10646 then the program is ill-formed

Or is that implied?

**Comment by tahonermann** [comment]
This is now tracked at https://github.com/sg16-unicode/sg16/issues/8
